[versions]
detekt = "2.0.0-alpha.5"
kotlin = "2.4.0"
mavenPublish = "0.37.0"

[libraries]
detekt-rules-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }

# Build-logic dependencies
mavenPublish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish-base = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublish" }

# Convention plugins defined by this project
ackeecz-detektconfig-publishing = { id = "ackeecz.detektconfig.publishing" }
